apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-dns
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: curlimages/curl:8.6.0
        command: ['sh', '-c', 'curl http://crudite-service.default:8080/ding']